# Generated by Django 4.2.6 on 2024-07-30 07:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kaps_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available_brands', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_date_to_apply', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('inspection_rating', models.IntegerField()),
                ('reg_year', models.IntegerField()),
                ('reg_month', models.CharField(blank=True, max_length=10, null=True)),
                ('km_driven', models.IntegerField()),
                ('rto', models.CharField(max_length=100)),
                ('insurance_validity', models.DateField()),
                ('insurance_type', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('finance_available', models.BooleanField(default=False)),
                ('emi', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('engine_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('suspension_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('brakes_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('transmission_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('interior_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('wheels_tyres_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available_fuel_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HappinessClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_image', models.ImageField(blank=True, upload_to='happiness_club/')),
                ('owner_info', models.CharField(max_length=100)),
                ('testimonial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transmission_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_test', models.BooleanField(default=True)),
                ('car_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='core.cars')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='SellYourCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_reg_number', models.CharField(max_length=50)),
                ('car_model', models.CharField(blank=True, max_length=50, null=True)),
                ('registered_year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ImageField(blank=True, null=True, upload_to='sell_car_images/')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_name', to='core.brand')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_fuel', to='core.fuel_type')),
                ('proposed_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selled_staf', to='Kaps_admin.crm_profile')),
                ('proposed_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selled_user', to='core.userlogin')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fueltype', to='core.fuel_type'),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_type', to='core.transmission'),
        ),
        migrations.CreateModel(
            name='Car_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_image', models.ImageField(upload_to='Car_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Book_now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_test', models.BooleanField(default=False)),
                ('car_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_data', to='core.cars')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_data', to='core.userlogin')),
            ],
        ),
    ]
