# Generated by Django 4.2.6 on 2024-07-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='variant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
