# Generated by Django 5.0.7 on 2024-08-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cars_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='model',
        ),
        migrations.RemoveField(
            model_name='happinessclub',
            name='owner_info',
        ),
        migrations.RemoveField(
            model_name='happinessclub',
            name='owner_name',
        ),
    ]
